apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List every file you want to deploy in this environment
resources:
  - namespace.yaml
  - secrets.yaml
  - networkpolicy.yaml
  - service.yaml
  - deployment.yaml
