apiVersion: v1
kind: Service
metadata:
  name: secure-service
  namespace: secure-dev
spec:
  type: ClusterIP # Keeps the service internal to your machine/cluster
  selector:
    app: secure-app # Matches the label in your Deployment and NetPolicy
  ports:
    - protocol: TCP
      port: 80       # The port the Service listens on
      targetPort: 8080 # The port the Pod is actually running on
