apiVersion: v1
kind: Service
metadata:
  name: secure-service
  namespace: secure-prod # <--- Update this
spec:
  type: ClusterIP
  selector:
    app: secure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
